name: Develop
on:
  push: 
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: google-task-creator
        path: |
          .
          !*.md
          !.git*
          !.github*
          !screen
